### ISSUE TITLE
pull in local system's dracut/kernel modules required for boot?

### ISSUE THREAD

**Issue by wgwoods** [rhinstaller/fedup#62]
How can we handle booting systems where `upgrade.img` is missing things like 3rd party dracut modules or kernel drivers?

## Problem Background

fedup's current design uses a generic dracut-built `upgrade.img` to boot your system. We do this because we want to use the kernel / SELinux policy / etc. from the new release during the upgrade.

Dracut images are _supposed_ to be generic enough to handle booting a system without needing any information other than what's in the boot arguments. 

Unfortunately, there are a lot of cases where that doesn't work, and then systems don't boot because the generic initramfs is missing something. Most commonly were missing some of the host's config files. So commit c2cc421 added code to pull config files out of the host's current initramfs into `upgrade.img`, which fixes a lot of stuff. But... not everything.

## The Actual Problem

[RHBZ#1199517] is a real-world case where we're missing more than just a config file. 

It's (apparently) possible to create a system that has its root on a [bcache] device. The [bcache-tools] package provides a [dracut module] that will set up the devices properly so you can find root. But the generic `upgrade.img` doesn't contain this module. So we can't find root, and thus can't start the upgrade. So the Big Questions are:

1. How can we identify what's needed to boot?
2. Once identified, how do we pull those things into our `upgrade.img` so that they'll actually work?

Some possible scenarios:
* Kernel modules: what if they require firmware?
* Dracut scripts: what if they require external binaries?
* Binaries: how do we get their libraries?
* Libraries: What if we need a _modified_ version of an existing library/binary?

[RHBZ#1199517]: https://bugzilla.redhat.com/show_bug.cgi?id=1199517
[bcache]: http://bcache.evilpiepirate.org/
[bcache-tools]: https://apps.fedoraproject.org/packages/bcache-tools
[dracut module]: http://evilpiepirate.org/git/bcache-tools.git/tree/dracut/module-setup.sh

**Comment by almereyda** [comment]
I wonder if this also counts for the reappearing `vfat` EFI partition mounting issue I'm experiencing (F21>F22) right now. ([F19 bug](https://bugzilla.redhat.com/show_bug.cgi?id=1044346), [F20 bug](https://bugzilla.redhat.com/show_bug.cgi?id=1174440))

Unfortunately I also cannot find the bug report from user _Robin_ of the [fedora users](https://lists.fedoraproject.org/pipermail/users/2015-April/459984.html) [mailing list](https://lists.fedoraproject.org/pipermail/users/2015-April/460055.html).

Because else, according to [Issues During Upgrade](https://fedoraproject.org/wiki/FedUp#Issues_During_Upgrade), I'm asked to file a bug report at [RHBZ](https://bugzilla.redhat.com/buglist.cgi?component=fedup-dracut&list_id=3531853&product=Fedora&resolution=---).

---

https://github.com/rhinstaller/fedup-dracut/releases/tag/0.7.1 seems to refer to this, too.

**Comment by wgwoods** [comment]
The real solution here is, basically, "don't use `upgrade.img`". It's more trouble than it's worth, as it turns out. 

For F23 and later upgrades should be handled by DNF (or a plugin), using systemd's [Offline Updates](http://freedesktop.org/wiki/Software/systemd/SystemUpdates/) facility - [dnf-plugin-fedup](https://github.com/wgwoods/dnf-plugin-fedup) is a proof-of-concept implementation.

The existing bugs will remain open, but this issue (and `fedup` itself) should be considered obsolete/deprecated.
